// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: testdata/example.proto

package testdata

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleEnum int32

const (
	ExampleEnum_EXAMPLE_ENUM_UNSPECIFIED ExampleEnum = 0
	ExampleEnum_VALID1                   ExampleEnum = 1
	ExampleEnum_VALID2                   ExampleEnum = 2
)

// Enum value maps for ExampleEnum.
var (
	ExampleEnum_name = map[int32]string{
		0: "EXAMPLE_ENUM_UNSPECIFIED",
		1: "VALID1",
		2: "VALID2",
	}
	ExampleEnum_value = map[string]int32{
		"EXAMPLE_ENUM_UNSPECIFIED": 0,
		"VALID1":                   1,
		"VALID2":                   2,
	}
)

func (x ExampleEnum) Enum() *ExampleEnum {
	p := new(ExampleEnum)
	*p = x
	return p
}

func (x ExampleEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_example_proto_enumTypes[0].Descriptor()
}

func (ExampleEnum) Type() protoreflect.EnumType {
	return &file_testdata_example_proto_enumTypes[0]
}

func (x ExampleEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleEnum.Descriptor instead.
func (ExampleEnum) EnumDescriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

type RequestMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequiredField    string                 `protobuf:"bytes,1,opt,name=required_field,json=requiredField,proto3" json:"required_field,omitempty"`
	ValidField       int64                  `protobuf:"varint,2,opt,name=valid_field,json=validField,proto3" json:"valid_field,omitempty"`
	ValidArgs        *duration.Duration     `protobuf:"bytes,3,opt,name=valid_args,json=validArgs,proto3" json:"valid_args,omitempty"`
	ValidRepeated    []string               `protobuf:"bytes,4,rep,name=valid_repeated,json=validRepeated,proto3" json:"valid_repeated,omitempty"`
	RequiredRepeated []string               `protobuf:"bytes,5,rep,name=required_repeated,json=requiredRepeated,proto3" json:"required_repeated,omitempty"`
	ValidMap         map[string]string      `protobuf:"bytes,6,rep,name=valid_map,json=validMap,proto3" json:"valid_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequiredMap      map[string]string      `protobuf:"bytes,7,rep,name=required_map,json=requiredMap,proto3" json:"required_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LengthField1     []string               `protobuf:"bytes,8,rep,name=length_field1,json=lengthField1,proto3" json:"length_field1,omitempty"`
	LengthField2     []string               `protobuf:"bytes,9,rep,name=length_field2,json=lengthField2,proto3" json:"length_field2,omitempty"`
	LengthValid      []string               `protobuf:"bytes,10,rep,name=length_valid,json=lengthValid,proto3" json:"length_valid,omitempty"`
	// Types that are valid to be assigned to OneofField:
	//
	//	*RequestMessage_OneofValid
	//	*RequestMessage_OneofValue
	//	*RequestMessage_OneofInner
	//	*RequestMessage_NestedMessage_
	OneofField                   isRequestMessage_OneofField              `protobuf_oneof:"oneof_field"`
	Value1                       int64                                    `protobuf:"varint,15,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2                       int64                                    `protobuf:"varint,16,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3                       int64                                    `protobuf:"varint,17,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4                       int64                                    `protobuf:"varint,18,opt,name=value4,proto3" json:"value4,omitempty"`
	InnerField                   *InnerMessage                            `protobuf:"bytes,19,opt,name=inner_field,json=innerField,proto3" json:"inner_field,omitempty"`
	RequiredInnerField           *InnerMessage                            `protobuf:"bytes,20,opt,name=required_inner_field,json=requiredInnerField,proto3" json:"required_inner_field,omitempty"`
	RepeatedInnerField           []*InnerMessage                          `protobuf:"bytes,21,rep,name=repeated_inner_field,json=repeatedInnerField,proto3" json:"repeated_inner_field,omitempty"`
	RepeatedRequiredInnerField   []*InnerMessage                          `protobuf:"bytes,22,rep,name=repeated_required_inner_field,json=repeatedRequiredInnerField,proto3" json:"repeated_required_inner_field,omitempty"`
	InnerNovalid                 *InnerNoValidMessage                     `protobuf:"bytes,23,opt,name=inner_novalid,json=innerNovalid,proto3" json:"inner_novalid,omitempty"`
	RequiredInnerNovalid         *InnerNoValidMessage                     `protobuf:"bytes,24,opt,name=required_inner_novalid,json=requiredInnerNovalid,proto3" json:"required_inner_novalid,omitempty"`
	RepeatedInnerNovalid         []*InnerNoValidMessage                   `protobuf:"bytes,25,rep,name=repeated_inner_novalid,json=repeatedInnerNovalid,proto3" json:"repeated_inner_novalid,omitempty"`
	RepeatedRequiredInnerNovalid []*InnerNoValidMessage                   `protobuf:"bytes,26,rep,name=repeated_required_inner_novalid,json=repeatedRequiredInnerNovalid,proto3" json:"repeated_required_inner_novalid,omitempty"`
	InnerEmpty                   *InnerEmptyMessage                       `protobuf:"bytes,27,opt,name=inner_empty,json=innerEmpty,proto3" json:"inner_empty,omitempty"`
	InnerWithInner               *InnerWithInnerMessage                   `protobuf:"bytes,28,opt,name=inner_with_inner,json=innerWithInner,proto3" json:"inner_with_inner,omitempty"`
	RepeatedInnerWithInner       []*InnerWithInnerMessage                 `protobuf:"bytes,29,rep,name=repeated_inner_with_inner,json=repeatedInnerWithInner,proto3" json:"repeated_inner_with_inner,omitempty"`
	NestedValid                  *RequestMessage_NestedMessage            `protobuf:"bytes,30,opt,name=nested_valid,json=nestedValid,proto3" json:"nested_valid,omitempty"`
	NestedNovalid                *RequestMessage_NestedNoValidMessage     `protobuf:"bytes,31,opt,name=nested_novalid,json=nestedNovalid,proto3" json:"nested_novalid,omitempty"`
	NestedFieldmask              *RequestMessage_NestedMessage            `protobuf:"bytes,32,opt,name=nested_fieldmask,json=nestedFieldmask,proto3" json:"nested_fieldmask,omitempty"`
	RequiredEnumField            ExampleEnum                              `protobuf:"varint,33,opt,name=required_enum_field,json=requiredEnumField,proto3,enum=testdata.ExampleEnum" json:"required_enum_field,omitempty"`
	MapParam                     map[string]string                        `protobuf:"bytes,34,rep,name=map_param,json=mapParam,proto3" json:"map_param,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInnerParam                map[string]*InnerMessage                 `protobuf:"bytes,35,rep,name=map_inner_param,json=mapInnerParam,proto3" json:"map_inner_param,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapNestedParam               map[string]*RequestMessage_NestedMessage `protobuf:"bytes,36,rep,name=map_nested_param,json=mapNestedParam,proto3" json:"map_nested_param,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CheckedString                string                                   `protobuf:"bytes,37,opt,name=checked_string,json=checkedString,proto3" json:"checked_string,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_testdata_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetRequiredField() string {
	if x != nil {
		return x.RequiredField
	}
	return ""
}

func (x *RequestMessage) GetValidField() int64 {
	if x != nil {
		return x.ValidField
	}
	return 0
}

func (x *RequestMessage) GetValidArgs() *duration.Duration {
	if x != nil {
		return x.ValidArgs
	}
	return nil
}

func (x *RequestMessage) GetValidRepeated() []string {
	if x != nil {
		return x.ValidRepeated
	}
	return nil
}

func (x *RequestMessage) GetRequiredRepeated() []string {
	if x != nil {
		return x.RequiredRepeated
	}
	return nil
}

func (x *RequestMessage) GetValidMap() map[string]string {
	if x != nil {
		return x.ValidMap
	}
	return nil
}

func (x *RequestMessage) GetRequiredMap() map[string]string {
	if x != nil {
		return x.RequiredMap
	}
	return nil
}

func (x *RequestMessage) GetLengthField1() []string {
	if x != nil {
		return x.LengthField1
	}
	return nil
}

func (x *RequestMessage) GetLengthField2() []string {
	if x != nil {
		return x.LengthField2
	}
	return nil
}

func (x *RequestMessage) GetLengthValid() []string {
	if x != nil {
		return x.LengthValid
	}
	return nil
}

func (x *RequestMessage) GetOneofField() isRequestMessage_OneofField {
	if x != nil {
		return x.OneofField
	}
	return nil
}

func (x *RequestMessage) GetOneofValid() string {
	if x != nil {
		if x, ok := x.OneofField.(*RequestMessage_OneofValid); ok {
			return x.OneofValid
		}
	}
	return ""
}

func (x *RequestMessage) GetOneofValue() int64 {
	if x != nil {
		if x, ok := x.OneofField.(*RequestMessage_OneofValue); ok {
			return x.OneofValue
		}
	}
	return 0
}

func (x *RequestMessage) GetOneofInner() *InnerMessage {
	if x != nil {
		if x, ok := x.OneofField.(*RequestMessage_OneofInner); ok {
			return x.OneofInner
		}
	}
	return nil
}

func (x *RequestMessage) GetNestedMessage() *RequestMessage_NestedMessage {
	if x != nil {
		if x, ok := x.OneofField.(*RequestMessage_NestedMessage_); ok {
			return x.NestedMessage
		}
	}
	return nil
}

func (x *RequestMessage) GetValue1() int64 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *RequestMessage) GetValue2() int64 {
	if x != nil {
		return x.Value2
	}
	return 0
}

func (x *RequestMessage) GetValue3() int64 {
	if x != nil {
		return x.Value3
	}
	return 0
}

func (x *RequestMessage) GetValue4() int64 {
	if x != nil {
		return x.Value4
	}
	return 0
}

func (x *RequestMessage) GetInnerField() *InnerMessage {
	if x != nil {
		return x.InnerField
	}
	return nil
}

func (x *RequestMessage) GetRequiredInnerField() *InnerMessage {
	if x != nil {
		return x.RequiredInnerField
	}
	return nil
}

func (x *RequestMessage) GetRepeatedInnerField() []*InnerMessage {
	if x != nil {
		return x.RepeatedInnerField
	}
	return nil
}

func (x *RequestMessage) GetRepeatedRequiredInnerField() []*InnerMessage {
	if x != nil {
		return x.RepeatedRequiredInnerField
	}
	return nil
}

func (x *RequestMessage) GetInnerNovalid() *InnerNoValidMessage {
	if x != nil {
		return x.InnerNovalid
	}
	return nil
}

func (x *RequestMessage) GetRequiredInnerNovalid() *InnerNoValidMessage {
	if x != nil {
		return x.RequiredInnerNovalid
	}
	return nil
}

func (x *RequestMessage) GetRepeatedInnerNovalid() []*InnerNoValidMessage {
	if x != nil {
		return x.RepeatedInnerNovalid
	}
	return nil
}

func (x *RequestMessage) GetRepeatedRequiredInnerNovalid() []*InnerNoValidMessage {
	if x != nil {
		return x.RepeatedRequiredInnerNovalid
	}
	return nil
}

func (x *RequestMessage) GetInnerEmpty() *InnerEmptyMessage {
	if x != nil {
		return x.InnerEmpty
	}
	return nil
}

func (x *RequestMessage) GetInnerWithInner() *InnerWithInnerMessage {
	if x != nil {
		return x.InnerWithInner
	}
	return nil
}

func (x *RequestMessage) GetRepeatedInnerWithInner() []*InnerWithInnerMessage {
	if x != nil {
		return x.RepeatedInnerWithInner
	}
	return nil
}

func (x *RequestMessage) GetNestedValid() *RequestMessage_NestedMessage {
	if x != nil {
		return x.NestedValid
	}
	return nil
}

func (x *RequestMessage) GetNestedNovalid() *RequestMessage_NestedNoValidMessage {
	if x != nil {
		return x.NestedNovalid
	}
	return nil
}

func (x *RequestMessage) GetNestedFieldmask() *RequestMessage_NestedMessage {
	if x != nil {
		return x.NestedFieldmask
	}
	return nil
}

func (x *RequestMessage) GetRequiredEnumField() ExampleEnum {
	if x != nil {
		return x.RequiredEnumField
	}
	return ExampleEnum_EXAMPLE_ENUM_UNSPECIFIED
}

func (x *RequestMessage) GetMapParam() map[string]string {
	if x != nil {
		return x.MapParam
	}
	return nil
}

func (x *RequestMessage) GetMapInnerParam() map[string]*InnerMessage {
	if x != nil {
		return x.MapInnerParam
	}
	return nil
}

func (x *RequestMessage) GetMapNestedParam() map[string]*RequestMessage_NestedMessage {
	if x != nil {
		return x.MapNestedParam
	}
	return nil
}

func (x *RequestMessage) GetCheckedString() string {
	if x != nil {
		return x.CheckedString
	}
	return ""
}

type isRequestMessage_OneofField interface {
	isRequestMessage_OneofField()
}

type RequestMessage_OneofValid struct {
	OneofValid string `protobuf:"bytes,11,opt,name=oneof_valid,json=oneofValid,proto3,oneof"`
}

type RequestMessage_OneofValue struct {
	OneofValue int64 `protobuf:"varint,12,opt,name=oneof_value,json=oneofValue,proto3,oneof"`
}

type RequestMessage_OneofInner struct {
	OneofInner *InnerMessage `protobuf:"bytes,13,opt,name=oneof_inner,json=oneofInner,proto3,oneof"`
}

type RequestMessage_NestedMessage_ struct {
	NestedMessage *RequestMessage_NestedMessage `protobuf:"bytes,14,opt,name=nested_message,json=nestedMessage,proto3,oneof"` // Note: field name == message name
}

func (*RequestMessage_OneofValid) isRequestMessage_OneofField() {}

func (*RequestMessage_OneofValue) isRequestMessage_OneofField() {}

func (*RequestMessage_OneofInner) isRequestMessage_OneofField() {}

func (*RequestMessage_NestedMessage_) isRequestMessage_OneofField() {}

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_testdata_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{1}
}

type InnerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnnerId      string                 `protobuf:"bytes,100,opt,name=innner_id,json=innnerId,proto3" json:"innner_id,omitempty"`
	InnerRepeated []string               `protobuf:"bytes,101,rep,name=inner_repeated,json=innerRepeated,proto3" json:"inner_repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerMessage) Reset() {
	*x = InnerMessage{}
	mi := &file_testdata_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMessage) ProtoMessage() {}

func (x *InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMessage.ProtoReflect.Descriptor instead.
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{2}
}

func (x *InnerMessage) GetInnnerId() string {
	if x != nil {
		return x.InnnerId
	}
	return ""
}

func (x *InnerMessage) GetInnerRepeated() []string {
	if x != nil {
		return x.InnerRepeated
	}
	return nil
}

type InnerNoValidMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerId       string                 `protobuf:"bytes,200,opt,name=inner_id,json=innerId,proto3" json:"inner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerNoValidMessage) Reset() {
	*x = InnerNoValidMessage{}
	mi := &file_testdata_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerNoValidMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerNoValidMessage) ProtoMessage() {}

func (x *InnerNoValidMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerNoValidMessage.ProtoReflect.Descriptor instead.
func (*InnerNoValidMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{3}
}

func (x *InnerNoValidMessage) GetInnerId() string {
	if x != nil {
		return x.InnerId
	}
	return ""
}

type InnerEmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerEmptyMessage) Reset() {
	*x = InnerEmptyMessage{}
	mi := &file_testdata_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerEmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerEmptyMessage) ProtoMessage() {}

func (x *InnerEmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerEmptyMessage.ProtoReflect.Descriptor instead.
func (*InnerEmptyMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{4}
}

type InnerWithInnerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerMessage  *InnerMessage          `protobuf:"bytes,300,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerWithInnerMessage) Reset() {
	*x = InnerWithInnerMessage{}
	mi := &file_testdata_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerWithInnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerWithInnerMessage) ProtoMessage() {}

func (x *InnerWithInnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerWithInnerMessage.ProtoReflect.Descriptor instead.
func (*InnerWithInnerMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{5}
}

func (x *InnerWithInnerMessage) GetInnerMessage() *InnerMessage {
	if x != nil {
		return x.InnerMessage
	}
	return nil
}

type RequestMessage_NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage_NestedMessage) Reset() {
	*x = RequestMessage_NestedMessage{}
	mi := &file_testdata_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage_NestedMessage) ProtoMessage() {}

func (x *RequestMessage_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage_NestedMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage_NestedMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RequestMessage_NestedMessage) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type RequestMessage_NestedNoValidMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage_NestedNoValidMessage) Reset() {
	*x = RequestMessage_NestedNoValidMessage{}
	mi := &file_testdata_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage_NestedNoValidMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage_NestedNoValidMessage) ProtoMessage() {}

func (x *RequestMessage_NestedNoValidMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage_NestedNoValidMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage_NestedNoValidMessage) Descriptor() ([]byte, []int) {
	return file_testdata_example_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RequestMessage_NestedNoValidMessage) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var File_testdata_example_proto protoreflect.FileDescriptor

const file_testdata_example_proto_rawDesc = "" +
	"\n" +
	"\x16testdata/example.proto\x12\btestdata\x1a\x1egoogle/protobuf/duration.proto\"\xb0\x15\n" +
	"\x0eRequestMessage\x12%\n" +
	"\x0erequired_field\x18\x01 \x01(\tR\rrequiredField\x12\x1f\n" +
	"\vvalid_field\x18\x02 \x01(\x03R\n" +
	"validField\x128\n" +
	"\n" +
	"valid_args\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\tvalidArgs\x12%\n" +
	"\x0evalid_repeated\x18\x04 \x03(\tR\rvalidRepeated\x12+\n" +
	"\x11required_repeated\x18\x05 \x03(\tR\x10requiredRepeated\x12C\n" +
	"\tvalid_map\x18\x06 \x03(\v2&.testdata.RequestMessage.ValidMapEntryR\bvalidMap\x12L\n" +
	"\frequired_map\x18\a \x03(\v2).testdata.RequestMessage.RequiredMapEntryR\vrequiredMap\x12#\n" +
	"\rlength_field1\x18\b \x03(\tR\flengthField1\x12#\n" +
	"\rlength_field2\x18\t \x03(\tR\flengthField2\x12!\n" +
	"\flength_valid\x18\n" +
	" \x03(\tR\vlengthValid\x12!\n" +
	"\voneof_valid\x18\v \x01(\tH\x00R\n" +
	"oneofValid\x12!\n" +
	"\voneof_value\x18\f \x01(\x03H\x00R\n" +
	"oneofValue\x129\n" +
	"\voneof_inner\x18\r \x01(\v2\x16.testdata.InnerMessageH\x00R\n" +
	"oneofInner\x12O\n" +
	"\x0enested_message\x18\x0e \x01(\v2&.testdata.RequestMessage.NestedMessageH\x00R\rnestedMessage\x12\x16\n" +
	"\x06value1\x18\x0f \x01(\x03R\x06value1\x12\x16\n" +
	"\x06value2\x18\x10 \x01(\x03R\x06value2\x12\x16\n" +
	"\x06value3\x18\x11 \x01(\x03R\x06value3\x12\x16\n" +
	"\x06value4\x18\x12 \x01(\x03R\x06value4\x127\n" +
	"\vinner_field\x18\x13 \x01(\v2\x16.testdata.InnerMessageR\n" +
	"innerField\x12H\n" +
	"\x14required_inner_field\x18\x14 \x01(\v2\x16.testdata.InnerMessageR\x12requiredInnerField\x12H\n" +
	"\x14repeated_inner_field\x18\x15 \x03(\v2\x16.testdata.InnerMessageR\x12repeatedInnerField\x12Y\n" +
	"\x1drepeated_required_inner_field\x18\x16 \x03(\v2\x16.testdata.InnerMessageR\x1arepeatedRequiredInnerField\x12B\n" +
	"\rinner_novalid\x18\x17 \x01(\v2\x1d.testdata.InnerNoValidMessageR\finnerNovalid\x12S\n" +
	"\x16required_inner_novalid\x18\x18 \x01(\v2\x1d.testdata.InnerNoValidMessageR\x14requiredInnerNovalid\x12S\n" +
	"\x16repeated_inner_novalid\x18\x19 \x03(\v2\x1d.testdata.InnerNoValidMessageR\x14repeatedInnerNovalid\x12d\n" +
	"\x1frepeated_required_inner_novalid\x18\x1a \x03(\v2\x1d.testdata.InnerNoValidMessageR\x1crepeatedRequiredInnerNovalid\x12<\n" +
	"\vinner_empty\x18\x1b \x01(\v2\x1b.testdata.InnerEmptyMessageR\n" +
	"innerEmpty\x12I\n" +
	"\x10inner_with_inner\x18\x1c \x01(\v2\x1f.testdata.InnerWithInnerMessageR\x0einnerWithInner\x12Z\n" +
	"\x19repeated_inner_with_inner\x18\x1d \x03(\v2\x1f.testdata.InnerWithInnerMessageR\x16repeatedInnerWithInner\x12I\n" +
	"\fnested_valid\x18\x1e \x01(\v2&.testdata.RequestMessage.NestedMessageR\vnestedValid\x12T\n" +
	"\x0enested_novalid\x18\x1f \x01(\v2-.testdata.RequestMessage.NestedNoValidMessageR\rnestedNovalid\x12Q\n" +
	"\x10nested_fieldmask\x18  \x01(\v2&.testdata.RequestMessage.NestedMessageR\x0fnestedFieldmask\x12E\n" +
	"\x13required_enum_field\x18! \x01(\x0e2\x15.testdata.ExampleEnumR\x11requiredEnumField\x12C\n" +
	"\tmap_param\x18\" \x03(\v2&.testdata.RequestMessage.MapParamEntryR\bmapParam\x12S\n" +
	"\x0fmap_inner_param\x18# \x03(\v2+.testdata.RequestMessage.MapInnerParamEntryR\rmapInnerParam\x12V\n" +
	"\x10map_nested_param\x18$ \x03(\v2,.testdata.RequestMessage.MapNestedParamEntryR\x0emapNestedParam\x12%\n" +
	"\x0echecked_string\x18% \x01(\tR\rcheckedString\x1a%\n" +
	"\rNestedMessage\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x1a,\n" +
	"\x14NestedNoValidMessage\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x1a;\n" +
	"\rValidMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10RequiredMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMapParamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x12MapInnerParamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.testdata.InnerMessageR\x05value:\x028\x01\x1ai\n" +
	"\x13MapNestedParamEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.testdata.RequestMessage.NestedMessageR\x05value:\x028\x01B\r\n" +
	"\voneof_field\"\x11\n" +
	"\x0fExampleResponse\"R\n" +
	"\fInnerMessage\x12\x1b\n" +
	"\tinnner_id\x18d \x01(\tR\binnnerId\x12%\n" +
	"\x0einner_repeated\x18e \x03(\tR\rinnerRepeated\"1\n" +
	"\x13InnerNoValidMessage\x12\x1a\n" +
	"\binner_id\x18\xc8\x01 \x01(\tR\ainnerId\"\x13\n" +
	"\x11InnerEmptyMessage\"U\n" +
	"\x15InnerWithInnerMessage\x12<\n" +
	"\rinner_message\x18\xac\x02 \x01(\v2\x16.testdata.InnerMessageR\finnerMessage*C\n" +
	"\vExampleEnum\x12\x1c\n" +
	"\x18EXAMPLE_ENUM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VALID1\x10\x01\x12\n" +
	"\n" +
	"\x06VALID2\x10\x022N\n" +
	"\x0eExampleService\x12<\n" +
	"\x03Get\x12\x18.testdata.RequestMessage\x1a\x19.testdata.ExampleResponse\"\x00B\vZ\t/testdatab\x06proto3"

var (
	file_testdata_example_proto_rawDescOnce sync.Once
	file_testdata_example_proto_rawDescData []byte
)

func file_testdata_example_proto_rawDescGZIP() []byte {
	file_testdata_example_proto_rawDescOnce.Do(func() {
		file_testdata_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)))
	})
	return file_testdata_example_proto_rawDescData
}

var file_testdata_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_example_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_testdata_example_proto_goTypes = []any{
	(ExampleEnum)(0),                            // 0: testdata.ExampleEnum
	(*RequestMessage)(nil),                      // 1: testdata.RequestMessage
	(*ExampleResponse)(nil),                     // 2: testdata.ExampleResponse
	(*InnerMessage)(nil),                        // 3: testdata.InnerMessage
	(*InnerNoValidMessage)(nil),                 // 4: testdata.InnerNoValidMessage
	(*InnerEmptyMessage)(nil),                   // 5: testdata.InnerEmptyMessage
	(*InnerWithInnerMessage)(nil),               // 6: testdata.InnerWithInnerMessage
	(*RequestMessage_NestedMessage)(nil),        // 7: testdata.RequestMessage.NestedMessage
	(*RequestMessage_NestedNoValidMessage)(nil), // 8: testdata.RequestMessage.NestedNoValidMessage
	nil,                       // 9: testdata.RequestMessage.ValidMapEntry
	nil,                       // 10: testdata.RequestMessage.RequiredMapEntry
	nil,                       // 11: testdata.RequestMessage.MapParamEntry
	nil,                       // 12: testdata.RequestMessage.MapInnerParamEntry
	nil,                       // 13: testdata.RequestMessage.MapNestedParamEntry
	(*duration.Duration)(nil), // 14: google.protobuf.Duration
}
var file_testdata_example_proto_depIdxs = []int32{
	14, // 0: testdata.RequestMessage.valid_args:type_name -> google.protobuf.Duration
	9,  // 1: testdata.RequestMessage.valid_map:type_name -> testdata.RequestMessage.ValidMapEntry
	10, // 2: testdata.RequestMessage.required_map:type_name -> testdata.RequestMessage.RequiredMapEntry
	3,  // 3: testdata.RequestMessage.oneof_inner:type_name -> testdata.InnerMessage
	7,  // 4: testdata.RequestMessage.nested_message:type_name -> testdata.RequestMessage.NestedMessage
	3,  // 5: testdata.RequestMessage.inner_field:type_name -> testdata.InnerMessage
	3,  // 6: testdata.RequestMessage.required_inner_field:type_name -> testdata.InnerMessage
	3,  // 7: testdata.RequestMessage.repeated_inner_field:type_name -> testdata.InnerMessage
	3,  // 8: testdata.RequestMessage.repeated_required_inner_field:type_name -> testdata.InnerMessage
	4,  // 9: testdata.RequestMessage.inner_novalid:type_name -> testdata.InnerNoValidMessage
	4,  // 10: testdata.RequestMessage.required_inner_novalid:type_name -> testdata.InnerNoValidMessage
	4,  // 11: testdata.RequestMessage.repeated_inner_novalid:type_name -> testdata.InnerNoValidMessage
	4,  // 12: testdata.RequestMessage.repeated_required_inner_novalid:type_name -> testdata.InnerNoValidMessage
	5,  // 13: testdata.RequestMessage.inner_empty:type_name -> testdata.InnerEmptyMessage
	6,  // 14: testdata.RequestMessage.inner_with_inner:type_name -> testdata.InnerWithInnerMessage
	6,  // 15: testdata.RequestMessage.repeated_inner_with_inner:type_name -> testdata.InnerWithInnerMessage
	7,  // 16: testdata.RequestMessage.nested_valid:type_name -> testdata.RequestMessage.NestedMessage
	8,  // 17: testdata.RequestMessage.nested_novalid:type_name -> testdata.RequestMessage.NestedNoValidMessage
	7,  // 18: testdata.RequestMessage.nested_fieldmask:type_name -> testdata.RequestMessage.NestedMessage
	0,  // 19: testdata.RequestMessage.required_enum_field:type_name -> testdata.ExampleEnum
	11, // 20: testdata.RequestMessage.map_param:type_name -> testdata.RequestMessage.MapParamEntry
	12, // 21: testdata.RequestMessage.map_inner_param:type_name -> testdata.RequestMessage.MapInnerParamEntry
	13, // 22: testdata.RequestMessage.map_nested_param:type_name -> testdata.RequestMessage.MapNestedParamEntry
	3,  // 23: testdata.InnerWithInnerMessage.inner_message:type_name -> testdata.InnerMessage
	3,  // 24: testdata.RequestMessage.MapInnerParamEntry.value:type_name -> testdata.InnerMessage
	7,  // 25: testdata.RequestMessage.MapNestedParamEntry.value:type_name -> testdata.RequestMessage.NestedMessage
	1,  // 26: testdata.ExampleService.Get:input_type -> testdata.RequestMessage
	2,  // 27: testdata.ExampleService.Get:output_type -> testdata.ExampleResponse
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_testdata_example_proto_init() }
func file_testdata_example_proto_init() {
	if File_testdata_example_proto != nil {
		return
	}
	file_testdata_example_proto_msgTypes[0].OneofWrappers = []any{
		(*RequestMessage_OneofValid)(nil),
		(*RequestMessage_OneofValue)(nil),
		(*RequestMessage_OneofInner)(nil),
		(*RequestMessage_NestedMessage_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_example_proto_rawDesc), len(file_testdata_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdata_example_proto_goTypes,
		DependencyIndexes: file_testdata_example_proto_depIdxs,
		EnumInfos:         file_testdata_example_proto_enumTypes,
		MessageInfos:      file_testdata_example_proto_msgTypes,
	}.Build()
	File_testdata_example_proto = out.File
	file_testdata_example_proto_goTypes = nil
	file_testdata_example_proto_depIdxs = nil
}
